/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdviseRouteImport } from './routes/advise'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as SensorsRouteImport } from './routes/sensors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviseRoute = AdviseRouteImport.update({
  id: '/advise',
  path: '/advise',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advise': typeof AdviseRoute
  '/guide': typeof GuideRoute
  '/sensors': typeof SensorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advise': typeof AdviseRoute
  '/guide': typeof GuideRoute
  '/sensors': typeof SensorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advise': typeof AdviseRoute
  '/guide': typeof GuideRoute
  '/sensors': typeof SensorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advise' | '/guide' | '/sensors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advise' | '/guide' | '/sensors'
  id: '__root__' | '/' | '/advise' | '/guide' | '/sensors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdviseRoute: typeof AdviseRoute
  GuideRoute: typeof GuideRoute
  SensorsRoute: typeof SensorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advise': {
      id: '/advise'
      path: '/advise'
      fullPath: '/advise'
      preLoaderRoute: typeof AdviseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdviseRoute: AdviseRoute,
  GuideRoute: GuideRoute,
  SensorsRoute: SensorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
